### ISSUE TITLE
Only admin can toggle a GPIO

### ISSUE THREAD

**Issue by KoenVanduffel** [catgiggle/OctoPrint-GpioControl#12]
I noticed in version 1.0.4 (probably was similar before but I never used an earlier version) that only an admin is allowed to toggle a GPIO. After updating to 1.0.7 this has not changed. Is there a particular setting that will enable the buttons for operators or is this by design?
FYI OctoLight can be operated by operator level.

**Comment by catgiggle** [comment]
This is by design. But it makes sense to grant access to operators as well.

**Comment by catgiggle** [comment]
Implemented with v1.0.8.

**Comment by KoenVanduffel** [comment]
Sorry for the late comment. Thanks, this works as expected now!
