### ISSUE TITLE
Off Button is almost not visible

### ISSUE THREAD

**Issue by DarthVad3r013** [catgiggle/OctoPrint-GpioControl#6]
Hello,
The plugin works fine but the off button is almost not visible on the browser.
I try with chrome on pc and mobile. The issue is the same.
I don't try with firefox or edge. 

![Screenshot_2021-02-20-10-27-10-048_com android chrome](https://user-images.githubusercontent.com/79338289/108590937-60091b00-7366-11eb-8a2e-21edc5d6da3c.jpg)

![Screenshot_2021-02-20-10-26-08-051_com android chrome](https://user-images.githubusercontent.com/79338289/108590947-77e09f00-7366-11eb-901f-ee209bd5d399.jpg)

**Comment by catgiggle** [comment]
Thanks for issue. This is interesting because I tested this on Firefox and Chrome. On both everything looks fine. But I will investigate what is going on.

**Comment by catgiggle** [comment]
Got it! Look for a version 1.0.2 which fix this

**Comment by DarthVad3r013** [comment]
It seems working with the 1.0.3 
Thanks a lot

**Comment by JeffreyFalgout** [comment]
Works for me too, thanks!
